<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerATQxJzc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerATQxJzc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerATQxJzc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerATQxJzc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerATQxJzc\App_KernelDevDebugContainer([
    'container.build_hash' => 'ATQxJzc',
    'container.build_id' => '9f76243c',
    'container.build_time' => 1744531410,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerATQxJzc');
